uos make puppet-wechat great again
wechaty/puppet-wechat pull request #206
Opened 2022-07-13 16:28 UTC by leochen-g

uos 协议又可以重新使用了

2022-07-13 16:29 UTC, leochen-g commented
有个lint 报错好像是项目之前就有的报错，是数据没有初始化，和本次提交无管

2022-07-14 00:47 UTC, LIUHanyang96 commented
关注一下

2022-07-14 01:55 UTC, lx0758 commented
mark

2022-07-14 02:40 UTC, huan requested changes
Thanks for the fix!

Please follow my reviews, and also remember to make sure the CI turns green before we can continue reviewing this PR!

2022-07-14 02:40 UTC, huan commented on package.json
> +    "qrcode-terminal": "^0.12.0",
Please remove unrelated dependencies.

2022-07-14 02:40 UTC, huan commented on src/puppet-wechat.ts
> +  token?           : string
Could you please explain what's this `token` for? It seems that it does not been referenced in the new code.

2022-07-14 03:42 UTC, huan commented
LGTM

2022-07-14 03:42 UTC, huan approved these changes

2022-07-14 03:42 UTC, merged